import { acessoAtual, exigirPaginaAcesso, exigirPermissaoAcesso } from "@/lib/acesso/servidor";
import { podeExibirAcao } from "@/components/acao-autorizada";
import Link from "next/link";
import { LinkGovernanca } from "@/components/link-governanca";
import { BotaoUnificacao } from "@/components/botao-unificacao";
import { notFound } from "next/navigation";
import { Card, Dinheiro, PageHeader, Sigilo, btnPrimario, btnSecundario, inputBase } from "@/components/ui";
import { EstadoUnificado, OrigensUnificadas, dataUnificada, exigirPerfilUnificacao, hrefUnificacao, mensagemUnificacao, motivoUnificacao, primeiroParametro, type ParametrosUnificacao } from "@/components/operacao-unificada";
import { detalheUnificado } from "@/lib/consultas/unificacao";
import { ROTULOS_DOMINIO, type CampoFonte, type FonteUnificacao, type LinhaUnificada } from "@/lib/unificacao/tipos";
import { resolverUnificacao } from "../actions";
import { origensDoRegistro } from "@/lib/unificacao/origens";
import { ImpactoConsolidacao } from "@/components/situacao-consolidacao";

export const metadata = { title: "Conferir registro — Unificação — Brisa" };
export const dynamic = "force-dynamic";
const CAMPOS_RESERVADOS = new Set(["taxa", "administracao", "composicao"]);
const campoVisivel = (chave: string) => !CAMPOS_RESERVADOS.has(chave);
function Campo({ campo }: { campo?: CampoFonte }) {
  if (!campo || campo.valor === null || campo.valor === "") return <span className="text-tinta-suave">Não informado</span>;
  if (campo.tipo === "dinheiro" && typeof campo.valor === "number") return <Sigilo><Dinheiro centavos={campo.valor} /></Sigilo>;
  return <span className="break-words">{campo.valor}</span>;
}
function Comparacao({ registro, destino }: { registro: FonteUnificacao; destino: FonteUnificacao }) {
  const campos = [...new Set([...Object.keys(registro.campos), ...Object.keys(destino.campos)])].filter(campoVisivel);
  return <div className="tabela-scroll overflow-x-auto rounded-lg border border-contorno" role="region" aria-label="Tabela com rolagem horizontal" tabIndex={0}><table className="tabela"><thead><tr><th>Campo</th><th className="min-w-[230px]"><span className="mb-2 block">Este registro · {registro.titulo}</span><OrigensUnificadas origens={origensDoRegistro(registro)} /></th><th className="min-w-[230px]"><span className="mb-2 block">Principal que será mantido · {destino.titulo}</span><OrigensUnificadas origens={origensDoRegistro(destino)} /></th></tr></thead><tbody>{campos.map((chave) => { const a = registro.campos[chave]; const b = destino.campos[chave]; const diverge = a?.valor != null && b?.valor != null && String(a.valor) !== String(b.valor); return <tr key={chave} className={diverge ? "bg-amber-50/50" : ""}><td className="text-xs text-tinta-suave">{a?.rotulo ?? b?.rotulo}{diverge ? <span className="mt-1 block text-[10px] font-semibold text-amber-800">Valores diferentes</span> : null}</td><td className="max-w-[380px] whitespace-normal!"><Campo campo={a} /></td><td className="max-w-[380px] whitespace-normal!"><Campo campo={b} /></td></tr>; })}</tbody></table></div>;
}
async function FormularioDecisao({ registro, acao, destino }: { registro: LinhaUnificada; acao: "VINCULAR" | "DISTINTO" | "REABRIR"; destino?: LinhaUnificada }) {
  if (!podeExibirAcao(await acessoAtual(), { permissao: ["unificacao.editar", "pagamentos.conciliar"], perfis: ["ADMINISTRADOR", "FINANCEIRO"] })) return null;
  const vincular = acao === "VINCULAR";
  return <form action={resolverUnificacao} className="mt-4 space-y-3 rounded-lg border border-contorno bg-slate-50/60 p-4">
    <input type="hidden" name="chave" value={registro.chave} /><input type="hidden" name="versao" value={registro.versao} /><input type="hidden" name="acao" value={acao} /><input type="hidden" name="hashFonte" value={registro.hash} />
    {destino ? <><input type="hidden" name="destinoChave" value={destino.chave} /><input type="hidden" name="hashDestino" value={destino.hash} /></> : null}
    <p className="text-xs leading-relaxed text-tinta">{vincular ? <>Vincular <strong>{registro.titulo}</strong> ao registro <strong>{destino?.titulo}</strong>. Os valores do registro principal prevalecem e a fonte acrescenta contexto. Esta ocorrência deixa de contar separadamente, sem apagar nenhuma linha de origem.</> : acao === "DISTINTO" ? "Confirmar que este registro representa uma ocorrência diferente. Ele permanece independente; quando financeiro, válido e não cancelado nem informativo, entra nos totais." : "Reabrir esta decisão para uma nova análise das fontes e correspondências."}</p>
    <label className="block text-xs font-semibold text-tinta-suave">Justificativa<textarea name="justificativa" minLength={8} maxLength={500} required rows={2} className={`${inputBase} mt-1 w-full`} placeholder="Descreva a evidência conferida: documento, contrato, competência ou referência." /></label>
    <label className="flex items-start gap-2 text-xs text-tinta"><input type="checkbox" required className="mt-0.5" /><span>{vincular ? "Conferi a comparação e confirmo que são o mesmo registro." : acao === "DISTINTO" ? "Conferi as correspondências e confirmo que é um registro diferente." : "Confirmo a reabertura para revisão."}</span></label>
    <BotaoUnificacao className={btnPrimario}>{vincular ? "São o mesmo registro · confirmar vínculo" : acao === "DISTINTO" ? "São registros diferentes · confirmar" : "Reabrir decisão"}</BotaoUnificacao>
  </form>;
}
export default async function Pagina({ params, searchParams }: { params: Promise<{ chave: string }>; searchParams: Promise<ParametrosUnificacao> }) {
  await exigirPaginaAcesso("/unificacao/[chave]");
  await exigirPermissaoAcesso("cadastros.sensiveis", { global: true });
  await exigirPerfilUnificacao();
  const podeEditar = podeExibirAcao(await acessoAtual(), { permissao: ["unificacao.editar", "pagamentos.conciliar"], perfis: ["ADMINISTRADOR", "FINANCEIRO"] });
  const [{ chave: chaveParam }, sp] = await Promise.all([params, searchParams]);
  let chave: string;
  try { chave = decodeURIComponent(chaveParam); } catch { notFound(); }
  const buscaDestino = (primeiroParametro(sp.buscarDestino) ?? "").slice(0, 120);
  const detalhe = await detalheUnificado(chave, buscaDestino);
  if (!detalhe) notFound();
  const { registro, candidatos, fontes, historico, baixas } = detalhe;
  const fontesPlanilha = fontes.filter(fonte => typeof fonte.proveniencia?.arquivo === "string");
  const destinoSelecionado = candidatos.find((c) => c.chave === primeiroParametro(sp.destino));
  const podeResolver = podeEditar && ["PENDENTE", "REVISAR", "ATIVO"].includes(registro.estado) && registro.qualidade === "OK";
  const podeDistinguir = podeEditar && ["PENDENTE", "REVISAR", "ATIVO"].includes(registro.estado) && registro.qualidade === "OK";
  return <div>
    <PageHeader titulo={registro.titulo} descricao={`${ROTULOS_DOMINIO[registro.dominio]} · ${registro.descricao}`} acoes={<><Link href="/unificacao" className={btnSecundario}>Voltar à conferência</Link>{registro.href ? <Link href={registro.href} className={btnPrimario}>Abrir cadastro / lançamento</Link> : null}{["RECEBER", "PAGAR"].includes(registro.dominio) && <LinkGovernanca tipo="TITULO" id={registro.chave}>Descartar duplicata</LinkGovernanca>}</>} />
    {primeiroParametro(sp.erro) ? <Card nivel="critico" className="mb-4 p-4 text-sm">{primeiroParametro(sp.erro)}</Card> : null}{primeiroParametro(sp.ok) ? <Card nivel="otimo" className="mb-4 p-4 text-sm">{mensagemUnificacao(primeiroParametro(sp.ok)!)}</Card> : null}
    <Card className="mb-5 p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="mb-2 text-xs font-semibold text-tinta-suave">De onde veio</h2><OrigensUnificadas origens={origensDoRegistro(registro)} /></div><div><h2 className="mb-2 text-xs font-semibold text-tinta-suave">Situação atual</h2><EstadoUnificado item={registro} /></div></div><ImpactoConsolidacao item={registro} className="mt-4" /><p className="mt-2 text-xs text-tinta-suave">A situação acima é o tratamento atual na consulta, não um comprovante de pagamento nem de auditoria manual. Para verificar conferências anteriores, consulte o histórico abaixo.</p>{registro.avisos.length || registro.divergencias.length ? <ul className="mt-3 space-y-1 text-xs text-amber-800">{[...new Set([...registro.avisos, ...registro.divergencias])].map((aviso) => <li key={aviso}>{motivoUnificacao(aviso)}</li>)}</ul> : null}</Card>
    {registro.origem === "WIDESYS" && ["RECEBER", "PAGAR"].includes(registro.dominio) ? <Card nivel="atencao" className="mb-5 p-4"><h2 className="text-sm font-bold">Conferência antes de emissão bancária</h2><p className="mt-1 text-xs leading-relaxed text-tinta-suave">Confira o contrato, o saldo, os dados do pagador e a conta emissora. A unificação deste título não emite boletos automaticamente.</p></Card> : null}
    <div className="mb-5 grid gap-5 xl:grid-cols-[minmax(0,1.3fr)_minmax(0,1fr)]">
      <Card className="p-5"><h2 className="text-sm font-bold">1. Confira este registro</h2><dl className="mt-4 grid gap-x-6 gap-y-4 sm:grid-cols-2">{Object.entries(registro.campos).filter(([chaveCampo]) => campoVisivel(chaveCampo)).map(([chaveCampo, campo]) => <div key={chaveCampo} className="min-w-0 border-b border-contorno pb-3"><dt className="mb-1 text-[10px] font-semibold uppercase tracking-wide text-tinta-suave">{campo.rotulo}</dt><dd className="text-xs"><Campo campo={campo} /></dd></div>)}</dl></Card>
      <Card className="p-5"><h2 className="text-sm font-bold">Qual decisão tomar?</h2><ol className="mt-3 list-decimal space-y-3 pl-4 text-xs leading-relaxed text-tinta-suave"><li>Compare a identificação, a referência do imóvel ou contrato, a competência e os valores das duas fontes.</li><li>Se for a mesma ocorrência, escolha o registro principal e confirme o vínculo. Os valores atuais do principal prevalecem.</li><li>Se as evidências mostrarem ocorrências diferentes, confirme “registro distinto”. Nome e valor, sozinhos, não comprovam identidade.</li></ol>{registro.qualidade !== "OK" ? <p className="mt-4 rounded-lg bg-amber-50 p-3 text-xs text-amber-900">Este registro tem uma inconsistência ou ausência na origem. Confira a captura e corrija a origem antes de incluí-lo no consolidado.</p> : null}{podeDistinguir ? <details className="mt-4 border-t border-contorno pt-4"><summary className="cursor-pointer text-xs font-semibold text-oliva-escura">Conferi: é um registro independente</summary><FormularioDecisao registro={registro} acao="DISTINTO" /></details> : null}{podeEditar && (registro.estado === "VINCULADO" || historico.length) ? <details className="mt-4 border-t border-contorno pt-4"><summary className="cursor-pointer text-xs font-semibold text-tinta-suave">Reabrir decisão anterior</summary><FormularioDecisao registro={registro} acao="REABRIR" /></details> : null}</Card>
    </div>
    {origensDoRegistro(registro).includes("BRISA") ? <Card className="mb-5 p-4"><h2 className="text-sm font-bold">Inclusão no Brisa: origem ainda a confirmar</h2><p className="mt-2 text-xs leading-relaxed text-tinta-suave">Há uma fonte sem evidência suficiente para identificar como entrou no sistema. Não a classificamos como manual: cadastros e lançamentos antigos também podem ter vindo das planilhas iniciais.</p></Card> : null}
    {fontesPlanilha.length ? <Card className="mb-5 p-5"><h2 className="text-sm font-bold">Evidências de origem nas planilhas</h2><p className="mt-1 text-xs text-tinta-suave">Referências comprovadas de arquivos vinculados a este registro, sem somar a fonte novamente.</p><ul className="mt-3 space-y-3">{fontesPlanilha.map(fonte => <li key={fonte.chave} className="break-words border-l-2 border-contorno pl-3 text-xs text-tinta-suave"><span className="font-semibold text-tinta">{String(fonte.proveniencia!.arquivo)}</span>{typeof fonte.proveniencia!.aba === "string" ? ` · Aba: ${fonte.proveniencia!.aba}` : ""}{typeof fonte.proveniencia!.linha === "number" ? ` · Linha: ${fonte.proveniencia!.linha}` : ""}</li>)}</ul></Card> : null}
    {baixas.length ? <Card className="mb-5 overflow-hidden"><div className="border-b border-contorno p-5"><h2 className="text-sm font-bold">Histórico de pagamentos do título</h2><p className="mt-1 text-xs text-tinta-suave">Trilha histórica das fontes; valores podem divergir do principal. Não soma novamente.</p></div><div className="tabela-scroll overflow-x-auto" role="region" aria-label="Tabela com rolagem horizontal" tabIndex={0}><table className="tabela tabela--acoes"><thead><tr><th>Data</th><th>Pagamento e origem</th><th>Situação</th><th className="text-right!">Valor</th><th /></tr></thead><tbody>{baixas.map((baixa) => <tr key={baixa.chave}><td>{dataUnificada(baixa.data)}</td><td className="whitespace-normal!"><p className="mb-1 text-xs">{baixa.descricao}</p><OrigensUnificadas origens={origensDoRegistro(baixa)} /></td><td><EstadoUnificado item={baixa} />{baixa.cancelado ? <p className="mt-1 text-xs text-erro">Estornado</p> : null}</td><td className="text-right!"><Sigilo><Dinheiro centavos={baixa.valor} /></Sigilo></td><td className="text-right!"><Link href={hrefUnificacao(baixa.chave)} className="text-xs font-semibold text-oliva-escura hover:underline">Ver detalhe</Link></td></tr>)}</tbody></table></div></Card> : null}
    <Card className="mb-5 p-5"><h2 className="text-sm font-bold">2. Encontre o registro já existente</h2><p className="mt-1 text-xs text-tinta-suave">As sugestões são pistas, não duplicatas confirmadas. Busque pelo nome ou referência e abra a comparação antes de decidir.</p><form action={hrefUnificacao(registro.chave)} className="mt-3 flex flex-wrap gap-2"><label className="min-w-0 flex-1"><span className="sr-only">Buscar registro principal</span><input name="buscarDestino" defaultValue={buscaDestino} className={`${inputBase} w-full`} placeholder="Nome ou referência do registro principal" /></label><button className={btnSecundario}>Buscar para comparar</button></form>{candidatos.length ? <div className="mt-4 grid gap-3 md:grid-cols-2">{candidatos.map((candidato) => <div key={candidato.chave} className="rounded-lg border border-contorno p-4"><div className="mb-2 flex flex-wrap gap-2"><OrigensUnificadas origens={origensDoRegistro(candidato)} /><EstadoUnificado item={candidato} /></div><h3 className="text-sm font-semibold">{candidato.titulo}</h3><p className="mt-1 text-xs text-tinta-suave">{candidato.descricao}</p><p className="mt-2 text-[11px] text-tinta-suave">{registro.candidatos.find((c) => c.chave === candidato.chave)?.motivos.map(motivoUnificacao).join(" · ") ?? "Resultado de busca · identidade a conferir"}</p><Link href={`${hrefUnificacao(registro.chave)}?destino=${encodeURIComponent(candidato.chave)}&buscarDestino=${encodeURIComponent(buscaDestino)}#comparacao`} className={`${btnSecundario} mt-3`}>Comparar lado a lado</Link></div>)}</div> : <p className="mt-4 text-sm text-tinta-suave">Nenhum registro encontrado. Busque por outra referência ou confira se são ocorrências distintas.</p>}</Card>
    {destinoSelecionado ? <Card className="mb-5 p-5" ><section id="comparacao"><h2 className="mb-1 text-sm font-bold">3. Confira o principal antes de confirmar</h2><p className="mb-4 text-xs text-tinta-suave">Principal proposto: {destinoSelecionado.titulo}. Seus valores serão mantidos; este registro não somará uma segunda vez. Diferenças estão destacadas e nenhum campo será sobrescrito por esta vinculação.</p><Comparacao registro={registro} destino={destinoSelecionado} />{podeResolver ? <FormularioDecisao registro={registro} destino={destinoSelecionado} acao="VINCULAR" /> : null}</section></Card> : null}
    {fontes.length > 1 ? <Card className="mb-5 p-5"><h2 className="mb-4 text-sm font-bold">Fontes preservadas neste registro</h2><div className="space-y-4">{fontes.filter((f) => f.chave !== registro.chave).map((fonte) => <div key={fonte.chave}><p className="mb-2 text-xs font-semibold">{fonte.titulo}</p><div className="mb-3"><OrigensUnificadas origens={origensDoRegistro(fonte)} /></div><Comparacao registro={fonte} destino={registro} /></div>)}</div></Card> : null}
    <Card className="p-5"><h2 className="text-sm font-bold">Histórico de decisões</h2>{historico.length ? <ol className="mt-4 space-y-3">{historico.map((h, i) => <li key={i} className="border-l-2 border-contorno pl-4"><p className="text-xs font-semibold">{({ VINCULAR: "Vínculo confirmado", DISTINTO: "Registro distinto confirmado", REABRIR: "Decisão reaberta" } as Record<string, string>)[h.acao] ?? h.acao} · {new Intl.DateTimeFormat("pt-BR", { dateStyle: "short", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(h.criadoEm)}</p><p className="mt-1 text-xs text-tinta-suave">{h.justificativa}</p></li>)}</ol> : <p className="mt-3 text-xs text-tinta-suave">Ainda não há decisão manual registrada para este item. Ele pode estar disponível por uma regra automática.</p>}</Card>
  </div>;
}
