import Link from "next/link";
import { Badge, Card, PageHeader, btnPrimario, btnSecundario, inputBase } from "@/components/ui";
import { exigirSessao } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { consultarGestaoAcessos, NOMES_TIPO } from "@/lib/acesso/gestao";
import { exigirPaginaAcesso } from "@/lib/acesso/servidor";
import { carteiraIrrestrita, lerPermissoes, PERMISSOES_ACESSO, PERFIS_ACESSO, TIPOS_ESCOPO } from "@/lib/acesso/politica";
import { salvarAcesso } from "./actions";

export const metadata = { title: "Usuários e acessos — Brisa" };
const ROTA = "/configuracoes/acessos";
const ROTULOS: Record<string, string> = { ADMINISTRADOR: "Administrador", SOCIO: "Sócio · somente leitura", CONTABILIDADE: "Contabilidade · somente leitura", FINANCEIRO: "Financeiro", OPERADOR: "Operador", CONSULTA: "Consulta · somente leitura" };
const permissoes = Object.entries(PERMISSOES_ACESSO).filter(([chave]) => !["comissoes.ver", "acessos.gerenciar"].includes(chave));
const permissoesDaCarteira = new Set(["carteira.ver", "cadastros.ver", "cadastros.sensiveis", "contratos.ver", "financeiro.ver", "relatorios.exportar"]);
const valor = (v: string | string[] | undefined) => Array.isArray(v) ? v[0] : v;
const classeRotulo = "block text-xs font-semibold text-tinta";

function Confirmar({ botao }: { botao: string }) {
  return <div className="mt-4 space-y-3 border-t border-contorno pt-4">
    <label className={classeRotulo}>Por que está alterando?<input name="motivo" minLength={5} maxLength={500} required className={`${inputBase} mt-1 block w-full`} placeholder="Ex.: carteira e responsabilidades conferidas com a gestão" /></label>
    <label className="flex items-start gap-2 text-xs leading-relaxed text-tinta-suave"><input type="checkbox" name="confirmado" value="sim" required className="mt-0.5" />Revisei a alteração e confirmo. As sessões afetadas serão encerradas.</label>
    <button className={btnPrimario}>{botao}</button>
  </div>;
}
function Identidade({ id, versao, acao }: { id: string; versao: number; acao: string }) {
  return <><input type="hidden" name="usuarioId" value={id} /><input type="hidden" name="versao" value={versao} /><input type="hidden" name="acao" value={acao} /></>;
}
function Perfil({ atual = "CONSULTA" }: { atual?: string }) {
  return <label className={classeRotulo}>Função-base<select name="perfil" defaultValue={atual} className={`${inputBase} mt-1 block w-full`}>{PERFIS_ACESSO.map(p => <option key={p} value={p}>{ROTULOS[p]}</option>)}</select></label>;
}
function Permissoes({ name, selecionadas, somenteLeitura = false }: { name: string; selecionadas: string[]; somenteLeitura?: boolean }) {
  return <><div className="mt-3 grid gap-2 sm:grid-cols-2 xl:grid-cols-3">{permissoes.filter(([p]) => !somenteLeitura || permissoesDaCarteira.has(p)).map(([chave, rotulo]) => <label key={chave} className="flex items-start gap-2 rounded-lg border border-contorno p-2.5 text-xs leading-relaxed text-tinta"><input type="checkbox" name={name} value={chave} defaultChecked={selecionadas.includes(chave)} className="mt-0.5" /><span>{rotulo}</span></label>)}</div>{somenteLeitura ? selecionadas.filter(p => !permissoesDaCarteira.has(p)).map(p => <input key={p} type="hidden" name={name} value={p} />) : null}</>;
}

export default async function PaginaAcessos({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  await exigirPaginaAcesso(ROTA);
  const sessao = await exigirSessao();
  const sp = await searchParams;
  const dados = await consultarGestaoAcessos(prisma, { usuarioId: sessao.sub, sessaoVersao: sessao.sv ?? 0 }, { usuarioId: valor(sp.editar), busca: valor(sp.q), tipo: valor(sp.tipo), buscaRecurso: valor(sp.recurso), papelId: valor(sp.funcao) });
  const u = dados.usuario;
  const proprio = u?.id === sessao.sub;
  const admin = u?.perfil === "ADMINISTRADOR";
  const somenteLeitura = !!u && ["SOCIO", "CONTABILIDADE", "CONSULTA"].includes(u.perfil);
  const restrito = dados.politica ? !carteiraIrrestrita(dados.politica) : false;
  return <div>
    <PageHeader titulo="Usuários e acessos" descricao="Defina o que cada pessoa pode fazer e quais clientes, imóveis e empreendimentos pode consultar. Comissões são exclusivas dos administradores." acoes={<Link href="#novo-usuario" className={btnPrimario}>Novo usuário</Link>} />
    {valor(sp.erro) ? <p role="alert" className="mb-4 rounded-lg border border-erro/30 bg-erro/5 p-4 text-sm text-erro">{valor(sp.erro)}</p> : null}
    {valor(sp.ok) ? <p role="status" className="mb-4 rounded-lg border border-oliva/30 bg-oliva/5 p-4 text-sm">{valor(sp.ok)}</p> : null}
    <Card className="mb-5 p-5"><ol className="grid gap-3 md:grid-cols-3">{[["1", "Escolha a função", "A função-base define os limites. Sócio, contabilidade e consulta nunca alteram dados."], ["2", "Revise as permissões", "Uma função personalizada substitui a base. Exceções são explícitas; bloqueios prevalecem."], ["3", "Defina a carteira", "Libere todos os cadastros ou uma carteira específica. Bloqueios são herdados e têm prioridade."]].map(([n, titulo, texto]) => <li key={n} className="flex items-start gap-3"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-oliva/10 text-xs font-bold text-oliva">{n}</span><div><h2 className="text-sm font-bold">{titulo}</h2><p className="mt-1 text-xs leading-relaxed text-tinta-suave">{texto}</p></div></li>)}</ol></Card>

    <Card className="mb-5 overflow-hidden">
      <form method="get" action={ROTA} className="flex flex-wrap items-end gap-2 border-b border-contorno p-4"><label className={`${classeRotulo} min-w-0 flex-1`}>Buscar usuário<input type="search" name="q" defaultValue={valor(sp.q)} className={`${inputBase} mt-1 block w-full`} placeholder="Nome ou login" /></label><button className={btnSecundario}>Buscar</button><Link href={ROTA} className={btnSecundario}>Limpar</Link></form>
      <div className="tabela-scroll overflow-x-auto" role="region" aria-label="Usuários e acessos" tabIndex={0}><table className="tabela tabela--acoes"><thead><tr><th>Usuário</th><th>Função-base</th><th>Situação</th><th>Abrangência declarada</th><th>Ações</th></tr></thead><tbody>{dados.usuarios.map(usuario => <tr key={usuario.id}><td><strong>{usuario.nome}</strong><span className="mt-1 block text-xs text-tinta-suave">{usuario.usuario}</span></td><td>{ROTULOS[usuario.perfil] ?? usuario.perfil}</td><td><Badge nivel={usuario.ativo ? "otimo" : "neutro"}>{usuario.ativo ? "Ativo" : "Inativo"}</Badge></td><td>{usuario.perfil === "ADMINISTRADOR" ? "Global · administrador" : usuario.acessoGlobal ? "Global, sujeita a bloqueios" : "Carteira selecionada"}</td><td><Link href={`${ROTA}?editar=${encodeURIComponent(usuario.id)}#usuario`} className="text-xs font-semibold text-oliva-escura hover:underline">Ver resumo e configurar</Link></td></tr>)}{!dados.usuarios.length ? <tr><td colSpan={5}>Nenhum usuário encontrado.</td></tr> : null}</tbody></table></div>
      <p className="px-4 py-3 text-xs text-tinta-suave">Até 100 usuários por consulta. Use a busca para localizar outros. Abrir o resumo não entra na conta do usuário.</p>
    </Card>

    {u ? <section id="usuario" className="mb-6 space-y-4">
      <Card className="p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-lg font-bold">{u.nome}</h2><p className="mt-1 text-xs text-tinta-suave">{u.usuario} · versão de acesso {u.acessoVersao}</p></div><Badge nivel={!u.ativo ? "neutro" : restrito ? "info" : "otimo"}>{!u.ativo ? "Acesso suspenso" : restrito ? "Carteira restrita" : somenteLeitura ? "Carteira global · consulta" : "Operação global"}</Badge></div>
        {proprio ? <p className="mt-3 rounded-lg bg-ambar/5 p-3 text-xs">Este é o seu usuário. Outro administrador deve revisar suas permissões ou redefinir sua senha.</p> : null}
        <h3 className="mt-4 text-xs font-bold uppercase tracking-wide">Permissões efetivas agora</h3><div className="mt-2 flex flex-wrap gap-2">{dados.politica?.permissoes.filter(p => !somenteLeitura || permissoesDaCarteira.has(p)).map(p => <span key={p} className="rounded-md border border-contorno bg-papel px-2 py-1 text-xs">{PERMISSOES_ACESSO[p]}</span>)}{!dados.politica?.permissoes.length ? <span className="text-xs text-tinta-suave">Nenhuma permissão ativa.</span> : null}</div>
        <p className="mt-3 text-xs leading-relaxed text-tinta-suave">{somenteLeitura ? "Sócio, contabilidade e consulta usam exclusivamente a Carteira autorizada e a ajuda, mesmo com abrangência global. Global significa todas as entidades nessa carteira; não libera telas operacionais. Exportação e dados pessoais dependem das permissões acima." : restrito ? "Este acesso usa somente a Carteira autorizada, em modo de consulta. Painéis, financeiro operacional, relatórios globais e alterações de dados não ficam disponíveis enquanto houver restrição ou qualquer bloqueio, mesmo com permissões marcadas." : "As telas globais dependem das permissões acima. A abrangência não concede por si só acesso a todos os módulos."}</p>
      </Card>
      {!proprio ? <>
        <Card className="p-5"><form action={salvarAcesso}><Identidade id={u.id} versao={u.acessoVersao} acao="SALVAR_USUARIO" /><h2 className="text-base font-bold">1. Função e responsabilidades</h2><div className="mt-4 grid gap-3 sm:grid-cols-2"><label className={classeRotulo}>Nome<input name="nome" required minLength={2} maxLength={100} defaultValue={u.nome} className={`${inputBase} mt-1 block w-full`} /></label><Perfil atual={u.perfil} /><label className={classeRotulo}>Função personalizada<select name="papelAcessoId" defaultValue={u.papelAcessoId ?? ""} disabled={admin} className={`${inputBase} mt-1 block w-full`}><option value="">Usar permissões da função-base</option>{dados.papeis.filter(p => p.ativo || p.id === u.papelAcessoId).map(p => <option key={p.id} value={p.id}>{p.nome}{p.ativo ? "" : " (inativa)"}</option>)}</select></label><label className="flex items-center gap-2 text-xs font-semibold"><input type="checkbox" name="acessoGlobal" value="sim" defaultChecked={u.acessoGlobal || admin} />{somenteLeitura ? "Todos os cadastros (sujeito a bloqueios)" : "Acesso global à operação (sujeito aos bloqueios da etapa 3)"}</label></div>
          <p className="mt-3 text-xs leading-relaxed text-tinta-suave">Administrador sempre tem acesso global e comissões. Para promovê-lo, remova antes funções personalizadas, exceções e regras de carteira. Trocar a função-base não libera automaticamente permissões de alteração.</p>
          <h2 className="mt-6 text-base font-bold">2. Exceções de permissão</h2>{admin ? <p className="mt-2 text-xs text-tinta-suave">O administrador possui todas as permissões. Exceções não se aplicam.</p> : <><details className="mt-3 rounded-lg border border-contorno p-3" open><summary className="cursor-pointer text-sm font-semibold">Liberar além da função</summary><Permissoes name="permissoesExtras" selecionadas={lerPermissoes(u.permissoesExtras)} somenteLeitura={somenteLeitura} /></details><details className="mt-3 rounded-lg border border-contorno p-3"><summary className="cursor-pointer text-sm font-semibold">Bloquear permissões da função</summary><Permissoes name="permissoesNegadas" selecionadas={lerPermissoes(u.permissoesNegadas)} somenteLeitura={somenteLeitura} /></details></>}
          <Confirmar botao="Salvar função e permissões" />
        </form></Card>
        {!admin ? <Card className="p-5"><h2 className="text-base font-bold">3. Clientes, imóveis e empreendimentos</h2><p className="mt-2 text-xs leading-relaxed text-tinta-suave">Liberar um empreendimento inclui suas unidades; bloquear um cadastro prevalece sobre a liberação herdada. Pessoas e imóveis do legado mantêm vínculos próprios. Se acesso global estiver desligado e não houver liberações, a carteira fica vazia.</p>
          <form action={ROTA} method="get" className="mt-4 grid items-end gap-3 sm:grid-cols-[1fr_2fr_auto]"><input type="hidden" name="editar" value={u.id} /><label className={classeRotulo}>Tipo<select name="tipo" defaultValue={dados.tipo} className={`${inputBase} mt-1 block w-full`}>{TIPOS_ESCOPO.map(t => <option key={t} value={t}>{NOMES_TIPO[t]}</option>)}</select></label><label className={classeRotulo}>Buscar cadastro<input name="recurso" defaultValue={valor(sp.recurso)} maxLength={100} className={`${inputBase} mt-1 block w-full`} placeholder="Nome, identificação ou referência" /></label><button className={btnSecundario}>Pesquisar</button></form>
          <form action={salvarAcesso} className="mt-4 rounded-lg border border-contorno bg-papel p-4"><Identidade id={u.id} versao={u.acessoVersao} acao="SALVAR_REGRA" /><input type="hidden" name="tipo" value={dados.tipo} /><div className="grid gap-3 sm:grid-cols-[2fr_1fr]"><label className={classeRotulo}>Cadastro localizado<select required name="recursoId" defaultValue="" className={`${inputBase} mt-1 block w-full`}><option value="">Selecione um cadastro</option>{dados.opcoes.map(o => <option key={o.id} value={o.id}>{o.nome}</option>)}</select></label><label className={classeRotulo}>Regra<select name="efeito" className={`${inputBase} mt-1 block w-full`}><option value="PERMITIR">Permitir consulta</option><option value="BLOQUEAR">Bloquear consulta</option></select></label></div><p className="mt-2 text-xs text-tinta-suave">Até 50 resultados. Refine a pesquisa se não localizar o cadastro.</p><Confirmar botao="Salvar regra de carteira" /></form>
          <div className="mt-4 space-y-2">{dados.regras.map(regra => <details key={regra.id} className="rounded-lg border border-contorno p-3"><summary className="cursor-pointer text-sm"><span className={regra.efeito === "BLOQUEAR" ? "font-semibold text-erro" : "font-semibold text-oliva-escura"}>{regra.efeito === "BLOQUEAR" ? "Bloqueado" : "Permitido"}</span> · {NOMES_TIPO[regra.tipo as keyof typeof NOMES_TIPO] ?? regra.tipo} · {regra.rotulo}</summary><form action={salvarAcesso}><Identidade id={u.id} versao={u.acessoVersao} acao="REMOVER_REGRA" /><input type="hidden" name="regraId" value={regra.id} /><p className="mt-3 text-xs text-tinta-suave">Remover uma regra de bloqueio pode ampliar acesso herdado. Nenhum cadastro será apagado.</p><Confirmar botao="Remover esta regra" /></form></details>)}{!dados.regras.length ? <p className="text-xs text-tinta-suave">Nenhuma regra individual cadastrada.</p> : null}</div>
        </Card> : null}
        <div className="grid gap-4 lg:grid-cols-2"><Card className="p-5"><form action={salvarAcesso}><Identidade id={u.id} versao={u.acessoVersao} acao="ALTERAR_STATUS" /><input type="hidden" name="ativo" value={u.ativo ? "nao" : "sim"} /><h2 className="text-base font-bold">{u.ativo ? "Suspender acesso" : "Reativar acesso"}</h2><p className="mt-2 text-xs text-tinta-suave">O histórico e os vínculos do usuário são preservados. Suspender revoga as sessões imediatamente.</p><Confirmar botao={u.ativo ? "Desativar usuário" : "Reativar usuário"} /></form></Card><Card className="p-5"><form action={salvarAcesso}><Identidade id={u.id} versao={u.acessoVersao} acao="REDEFINIR_SENHA" /><h2 className="text-base font-bold">Redefinir senha</h2><label className={`${classeRotulo} mt-3`}>Nova senha<input type="password" name="senha" minLength={12} maxLength={128} required autoComplete="new-password" className={`${inputBase} mt-1 block w-full`} /></label><p className="mt-2 text-xs text-tinta-suave">Entre 12 e 128 caracteres. Compartilhe por um canal seguro; a senha não aparece no histórico.</p><Confirmar botao="Redefinir e encerrar sessões" /></form></Card></div>
      </> : null}
    </section> : null}

    <Card className="mb-5 p-5" ><details id="novo-usuario"><summary className="cursor-pointer text-base font-bold">Criar novo usuário</summary><form action={salvarAcesso} className="mt-4"><input type="hidden" name="acao" value="CRIAR_USUARIO" /><div className="grid gap-3 sm:grid-cols-2"><label className={classeRotulo}>Nome<input name="nome" minLength={2} maxLength={100} required className={`${inputBase} mt-1 block w-full`} /></label><label className={classeRotulo}>Login<input name="login" minLength={3} maxLength={80} required autoComplete="off" pattern="[a-zA-Z0-9][a-zA-Z0-9._@\-]+" className={`${inputBase} mt-1 block w-full`} /></label><Perfil /><label className={classeRotulo}>Senha inicial<input type="password" name="senha" minLength={12} maxLength={128} autoComplete="new-password" required className={`${inputBase} mt-1 block w-full`} /></label></div><p className="mt-3 text-xs text-tinta-suave">Novos usuários começam sem acesso global e sem carteira liberada. Exceção: administrador tem acesso integral, inclusive a comissões. Depois da criação, revise as três etapas acima.</p><Confirmar botao="Criar usuário" /></form></details></Card>
    <Card className="mb-5 p-5"><details id="funcoes" open={!!dados.papel}><summary className="cursor-pointer text-base font-bold">Funções personalizadas reutilizáveis</summary><p className="mt-3 text-xs text-tinta-suave">Uma função por usuário, sem somar funções de carteiras diferentes. Alterações afetam todos os usuários associados e encerram suas sessões. Uma função inativa bloqueia todas as permissões dos associados.</p><div className="mt-3 flex flex-wrap gap-2"><Link href={`${ROTA}#funcoes`} className={btnSecundario}>Nova função</Link>{dados.papeis.map(p => <Link key={p.id} href={`${ROTA}?funcao=${encodeURIComponent(p.id)}#funcoes`} className={btnSecundario}>{p.nome}{p.ativo ? "" : " · inativa"}</Link>)}</div><form action={salvarAcesso} className="mt-4" key={dados.papel?.id ?? "nova-funcao"}><input type="hidden" name="acao" value="SALVAR_FUNCAO" /><input type="hidden" name="papelId" value={dados.papel?.id ?? ""} /><input type="hidden" name="versao" value={dados.papel?.versao ?? 0} /><div className="grid gap-3 sm:grid-cols-2"><label className={classeRotulo}>Nome da função<input name="nome" required minLength={2} maxLength={80} defaultValue={dados.papel?.nome ?? ""} className={`${inputBase} mt-1 block w-full`} /></label><label className={classeRotulo}>Descrição<input name="descricao" maxLength={400} defaultValue={dados.papel?.descricao ?? ""} className={`${inputBase} mt-1 block w-full`} /></label></div><label className="mt-3 flex items-center gap-2 text-xs"><input type="checkbox" name="ativo" value="sim" defaultChecked={dados.papel?.ativo ?? true} />Função ativa</label><Permissoes name="permissoes" selecionadas={lerPermissoes(dados.papel?.permissoes ?? "[]")} /><Confirmar botao={dados.papel ? "Atualizar função para os usuários associados" : "Criar função personalizada"} /></form></details></Card>
    <Card className="p-5"><h2 className="text-base font-bold">Histórico de decisões{u ? ` · ${u.nome}` : ""}</h2><p className="mt-1 text-xs text-tinta-suave">Últimas 20 decisões; senhas e hashes nunca são registrados.</p><ul className="mt-4 divide-y divide-contorno">{dados.eventos.map(evento => <li key={evento.id} className="py-3 text-xs"><span className="font-semibold">{evento.tipo.replaceAll("_", " ")} · {evento.autorNome}</span><p className="mt-1 text-tinta-suave">{evento.criadoEm.toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" })} · {evento.motivo}</p></li>)}{!dados.eventos.length ? <li className="text-xs text-tinta-suave">Nenhuma alteração registrada.</li> : null}</ul></Card>
  </div>;
}
