import { Badge, Card, PageHeader } from "@/components/ui";
import { exigirAcessoFiscal } from "@/lib/fiscal/acesso";
import { obterConfiguracaoFiscal } from "@/lib/fiscal/servico";
import { lerParametrosFiscais } from "@/lib/fiscal/dominio";
import { infraestruturaFiscal } from "@/lib/fiscal/focus";
import { AbasFiscais, AvisoFiscal, CampoFiscal, SelecaoFiscal, botaoFiscal } from "../_ui";
import { salvarConfiguracao } from "../actions";

export const dynamic = "force-dynamic";
export const metadata = { title: "Configuração fiscal — Brisa" };

export default async function ConfiguracaoFiscalPage({ searchParams }: { searchParams: Promise<{ erro?: string; ok?: string }> }) {
  await exigirAcessoFiscal();
  const config = await obterConfiguracaoFiscal();
  const params = await searchParams;
  const p = lerParametrosFiscais(config?.parametros ?? "{}");
  const infraHomologacao = infraestruturaFiscal("HOMOLOGACAO");
  const infraProducao = infraestruturaFiscal("PRODUCAO");
  return <div><PageHeader titulo="Configuração fiscal" descricao="NFS-e Goiânia · conta do provedor, emitente e regras tributárias revisadas com sua contabilidade."/><AbasFiscais atual="configuracao"/><AvisoFiscal {...params}/>
    <Card className="mb-5 p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-widest text-oliva">Conexão fiscal · Focus NFe</p><h2 className="mt-2 text-base font-bold text-tinta">Layout nacional. Autorizador municipal de Goiânia.</h2></div><Badge cor="ambar">Homologação obrigatória</Badge></div><p className="mt-3 text-xs leading-relaxed text-tinta-suave">Adaptador opcional, com conta e contratação próprias no provedor. Certificado e sua senha são cadastrados diretamente no ambiente seguro do provedor; o Brisa usa somente o token da empresa no servidor. Não cole certificado, senha ou token nestes campos.</p><div className="mt-4 grid gap-3 sm:grid-cols-3">{[["Token de homologação", infraHomologacao.token], ["Token de produção", infraProducao.token], ["Liberação no servidor", infraProducao.producaoLiberada]].map(([titulo, pronto])=><div className="rounded-lg border border-contorno bg-fundo p-3" key={String(titulo)}><p className="mb-2 text-xs font-semibold">{titulo}</p><Badge cor={pronto ? "verde" : "ambar"}>{pronto ? "Configurado" : "Pendente"}</Badge></div>)}</div><p className="mt-3 text-[11px] leading-relaxed text-tinta-suave">Na Focus, usar o produto NFS-e com layout nacional e endpoint v2/nfsen para Goiânia; não ativar a opção “Ambiente da NFS-e Nacional” para este fluxo municipal. Solicite a liberação de webservice e da faixa DPS ao provedor/município. O enquadramento pode exigir outro fluxo, especialmente MEI e mudanças de obrigatoriedade do Simples.</p><a href="https://focusnfe.com.br/guides/nfse/municipios-integrados/goiania-go/" target="_blank" rel="noreferrer" className="mt-3 inline-block text-xs font-semibold text-oliva-escura underline">Consultar orientação atual do provedor ↗</a></Card>
    <form action={salvarConfiguracao} className="space-y-5"><input type="hidden" name="versao" value={config?.atualizadoEm.toISOString() ?? ""}/>
      <Card className="p-5 sm:p-6"><h2 className="text-sm font-bold text-tinta">1. Identificação do emitente</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><CampoFiscal nome="razaoSocial" titulo="Razão social" valor={config?.razaoSocial} max={150}/><CampoFiscal nome="emitenteCnpj" titulo="CNPJ numérico do prestador" valor={config?.emitenteCnpj} max={24}/><CampoFiscal nome="inscricaoMunicipal" titulo="Inscrição municipal (CAE)" valor={config?.inscricaoMunicipal} max={15}/><SelecaoFiscal nome="ambiente" titulo="Ambiente" valor={config?.ambiente ?? "HOMOLOGACAO"} opcoes={[["HOMOLOGACAO","Homologação · sem validade fiscal"],["PRODUCAO","Produção · documento fiscal válido"]]}/><CampoFiscal nome="municipio" titulo="Município emissor" valor="5208707 · Goiânia/GO" somenteLeitura/><SelecaoFiscal nome="opcaoSimples" titulo="Enquadramento no Simples Nacional" valor={p.opcaoSimples} opcoes={[["1","Não optante"],["3","Optante · ME/EPP"]]} dica="MEI não é suportado por este fluxo municipal."/></div></Card>
      <Card className="p-5 sm:p-6"><h2 className="text-sm font-bold text-tinta">2. Serviço e enquadramento tributário</h2><p className="mt-1 text-xs leading-relaxed text-tinta-suave">Não há códigos de atividade ou alíquotas presumidos. Peça à contabilidade os códigos da atividade efetivamente prestada. Nesta versão: operação tributável, ISS não retido, serviço em Goiânia, tomador igual ao destinatário e sem deduções.</p><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><CampoFiscal nome="codigoTributacaoNacional" titulo="Tributação nacional ISS · 6 dígitos" valor={p.codigoTributacaoNacional} max={6}/><CampoFiscal nome="codigoTributacaoMunicipal" titulo="Tributação municipal · 3 dígitos" valor={p.codigoTributacaoMunicipal} max={3} obrigatorio={false} dica="Quando exigida para a atividade."/><CampoFiscal nome="codigoNbs" titulo="NBS · 9 dígitos" valor={p.codigoNbs} max={9}/><SelecaoFiscal nome="regimeEspecial" titulo="Regime especial de tributação" valor={p.regimeEspecial} opcoes={[["0","Nenhum · regime normal"]]}/><SelecaoFiscal nome="regimeApuracao" titulo="Apuração do Simples (se optante)" valor={p.regimeApuracao} obrigatorio={false} opcoes={[["1","Federais e municipal pelo Simples"],["2","Federais pelo Simples; ISS por fora"],["3","Federais e municipal por fora do Simples"]]} dica="Obrigatório para ME/EPP optante. Para não optante, o campo não será enviado."/><CampoFiscal nome="codigoIndicadorOperacao" titulo="Indicador de operação IBS/CBS · 6 dígitos" valor={p.codigoIndicadorOperacao} max={6}/><CampoFiscal nome="cstIbsCbs" titulo="CST IBS/CBS · 3 dígitos" valor={p.cstIbsCbs} max={3}/><CampoFiscal nome="classificacaoIbsCbs" titulo="Classificação IBS/CBS · 6 dígitos" valor={p.classificacaoIbsCbs} max={6}/></div></Card>
      <Card className="p-5 sm:p-6"><h2 className="text-sm font-bold text-tinta">3. Tributos aproximados e numeração</h2><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3"><SelecaoFiscal nome="tributosModo" titulo="Informação de tributos aproximados" valor={p.tributosModo} opcoes={[["PERCENTUAIS","Percentuais federal, estadual e municipal"],["SIMPLES","Percentual do Simples Nacional"],["NAO_INFORMAR","Não informar · conferir elegibilidade"]]}/><CampoFiscal nome="tributosFederal" titulo="Federal (%)" valor={p.tributosFederal} obrigatorio={false} max={5}/><CampoFiscal nome="tributosEstadual" titulo="Estadual (%)" valor={p.tributosEstadual} obrigatorio={false} max={5}/><CampoFiscal nome="tributosMunicipal" titulo="Municipal (%)" valor={p.tributosMunicipal} obrigatorio={false} max={5}/><CampoFiscal nome="tributosSimples" titulo="Simples Nacional (%)" valor={p.tributosSimples} obrigatorio={false} max={5}/><CampoFiscal nome="serieDps" titulo="Série DPS liberada" valor={p.serieDps} max={5} dica="De 1 a 49999, conforme liberação do provedor."/><CampoFiscal nome="proximoDps" titulo="Próximo número DPS disponível" valor={p.proximoDps} max={15} dica="Confirme a faixa com o provedor. Cada rascunho reserva um número, sem reutilização."/></div></Card>
      <Card className="p-5 sm:p-6"><h2 className="text-sm font-bold text-tinta">4. Ativação controlada</h2><div className="mt-4 space-y-4 text-xs leading-relaxed text-tinta"><label className="flex items-start gap-3"><input type="checkbox" name="habilitada" defaultChecked={config?.habilitada ?? false} className="mt-0.5"/><span>Habilitar transmissão neste ambiente. Cada documento continuará exigindo revisão, aprovação e confirmação manual.</span></label><label className="flex items-start gap-3"><input type="checkbox" name="homologacaoValidada" defaultChecked={config?.homologacaoValidada ?? false} className="mt-0.5"/><span>Conferi uma nota autorizada em homologação com o responsável fiscal e validei os parâmetros. O sistema exige a existência desse teste para aceitar a confirmação.</span></label><label className="flex items-start gap-3"><input type="checkbox" name="confirmarProducao" className="mt-0.5"/><span>Ao habilitar produção, confirmo que tenho autorização para emissão real pelo emitente, certificado válido e liberação municipal. Produção gera documentos com efeitos fiscais.</span></label></div><div className="mt-5 flex flex-wrap items-center gap-3"><button className={botaoFiscal}>Salvar configuração</button><span className="text-xs text-tinta-suave">Nenhuma emissão ou contratação é feita ao salvar.</span></div></Card>
    </form>
  </div>;
}
